In [ ]:
print('shashank')

shashank


In [ ]:
#libraries
import math as m

In [ ]:
#energy for wind turbine
v=float(input("Enter the wind speed in meter/second "))
r=float(input("Enter the radius of blade in metre"))
a=m.pi*(r**2)
cp=0.59 #Betz Limit
cg=float(input("enter the generator efficiency"))
nt=int(input("enter the no of winds turbine in one plant"))
rho=1.1906 
pw=0.5*rho*a*(v**3)*cp*cg*nt*2.7777*(10**(-7))

#environmental ascept
enw=7.5*(10**5) + 12*(10**7)*pw*365*24
#economical effect
ecw=1600*pw*365*24

Enter the wind speed in meter/second 15.2778
Enter the radius of blade in metre63.75
enter the generator efficiency0.9
enter the no of winds turbine in one plant300


In [ ]:
print(pw)
print(enw)
print(ecw)

1199.3051796776335
1260709605627128.2
16809461398.361713


In [ ]:
#for solar panel r is solar panel yield (%), H is annual average solar radiation on tilted panels and PR = Performan...


nefso=float(input("input efficiency of solar plant because of loss"))
AreaSo=float(input("input area of solar panel in m^2"))
RSo=float(input("solar panel yield %"))
PR=float(input("performance ratio"))
H=float(input("annual average solar radiation"))
Numberso=int(input("no of solar plates in one plant"))
pso=nefso*AreaSo*RSo*PR*H*Numberso*2.7777*(10**(-7))

#environmental ascept
enso=19*(10**5) + 40*(10**7)*pso*365*24
#economical effect
ecso=830*pso*365*24

input efficiency of solar plant because of loss0.9
input area of solar panel in m^21.7
solar panel yield %15.6
performance ratio0.75
annual average solar radiation1361
no of solar plates in one plant6000


In [ ]:
print(pso)
print(enso)
print(ecso)

40.604298047819995
142277462259561.28
295225730.24608964


In [ ]:
#for coal
mcoal=float(input("mass of coal used per second in tonnes"))
nefc=float(input("input efficiency of coal power plant"))
caf=float(input("input calorific value of coal in Mj/kg"))
pco=nefc*mcoal*caf*1000000*2.7777*(10**(-7))

#environmental ascept
enco=15*(10**5) + 1011.511*(10**7)*pco*365*24
#economical effect
ecco=3500*pco*365*24

mass of coal used per second in tonnes2.7
input efficiency of coal power plant0.33
input calorific value of coal in Mj/kg28.5


In [ ]:
print(pco)
print(enco)
print(ecco)

7.053552495
625003745648647.1
216261919.49670005


In [ ]:
#for petroleum
mpet=float(input("litre of crude oil per second"))
nefp=float(input("input efficiency of oil plant"))
cafp=float(input("input calorific value of crude oil Mj/Kg"))
densitycrude=850
ppe=nefp*mpet*cafp*densitycrude*1000000*2.7777*(10**(-7))

#environmental ascept
enpe=15*(10**5) + 966.1517*(10**7)*ppe*365*24
#economical effect
ecpe=600*ppe*365*24

litre of crude oil0.33
input efficiency of oil plant0.3028
input calorific value of crude oil Mj/Kg850


In [ ]:
print(ppe)
print(enpe)
print(ecpe)

20053.630149300003
1.6972367601302687e+18
105401880064.7208


In [ ]:
#for natural gas
mng=float(input("volume of natural gas in litre"))
nefng=float(input("input efficiency of natural gas plant"))
cafng=float(input("input calorific value of natural gas"))
densitygas=0.97
png=nefng*mng*densitygas*cafng*1000000*2.7777*(10**(-7))

#environmental ascept
enng=1*(10**5) + 412.7691*(10**7)*png*365*24
#economical effect
ecng=710*png*365*24

volume of natural gas in litre28.2
input efficiency of natural gas plant0.8
input calorific value of natural gas0.97


In [ ]:
print(png)
print(enng)
print(ecng)

5.896141570079999
213196066423454.94
36671642.10926956


In [ ]:
#for hydropower plant
height=float(input("height of hydroplant"))
area=float(input("enter area of plant"))
neffhydro=float(input("efficiency of hydroplant"))
phydro=neffhydro*1000*area*9.81*0.9*0.9*height*height*2.7777*(10**(-7))

#environmental ascept
enhydro=33*(10**5) + 24*(10**7)*phydro*365*24
#economical effect
echydro=2752*phydro*365*24

height of hydroplant20
enter area of plant11240.9530
efficiency of hydroplant0.54


In [ ]:
print(phydro)
print(enhydro)
print(echydro)

5359.154137480456
1.1267085661938908e+16
129195915552.39282


In [ ]:
#nuclear
mnu=float(input("mass of nuclear fuel"))
nefnu=float(input("input efficiency of nuclear"))
cafnu=float(input("input calorific value of nuclear"))
pnu=nefnu*mnu*cafnu*2.7777*(10**(-7))*1000000

#environmental ascept
ennu=0.3*(10**5) + 12*(10**7)*pnu*365*24
#economical effect
ecnu=6000*pnu*365*24

mass of nuclear fuel17.625
input efficiency of nuclear0.45
input calorific value of nuclear24000


In [ ]:
print(pnu)
print(ennu)
print(ecnu)

52873.519499999995
5.558064369842998e+16
2779032184919.9995


In [ ]:
#optimization functions
Power=pnu+phydro+png+ppe+pco+pw+pso
EnvironmentalFactor=ennu+enhydro+enng+enpe+enco+enw+enso
EconomicFactor=ecnu+echydro+ecng+ecpe+ecco+ecw+ecso

In [ ]:
#constraints
preq=float(input("Input power requirement in lakh units for one year"))

Power1=-1*preq*(10**5)
pextra=float(input("storage capacity of power  in lakh units for one year"))

Power2=-1*pextra*(10**5)


Input power requirement in lakh units for one year72
storage capacity of power  in lakh units for one year10


In [ ]:
print(Power1)

-7200000.0


In [ ]:
print(Power2)

-1000000.0


In [ ]:
!pip install pymoo

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.9 MB 4.8 MB/s 
     |████████████████████████████████| 80 kB 9.3 MB/s 
     |████████████████████████████████| 249 kB 52.1 MB/s 
     |████████████████████████████████| 207 kB 72.3 MB/s 
  Created wheel for grapheme: filename=grapheme-0.6.0-py3-none-any.whl size=210095 sha256=3aedeac4d403a4ccd3408a88ecb1e7689f087a8e87928f9cc0dd82ec7bb22e7c
  Stored in directory: /root/.cache/pip/wheels/71/fc/c8/142ef03b79c02b618fe80b9f2d01c25bd55f60b0c58eab3f0e
Successfully built grapheme


In [ ]:
max=10**3

In [ ]:
from pymoo.core.problem import ElementwiseProblem
from pymoo.core.variable import Real, Integer
class MultiObjectiveMixedVariableProblem(ElementwiseProblem):

    def __init__(self, **kwargs):
        vars = {
            "nnu": Integer(bounds=(0, max )),
            "nhydro": Integer(bounds=(0, max )),
            "nng": Integer(bounds=(0, max )),
            "npe": Integer(bounds=(0, max )),
            "nco": Integer(bounds=(0, max )),
            "nw": Integer(bounds=(0, max )),
            "nso": Integer(bounds=(0, max )),

           
        }
        super().__init__(vars=vars, n_obj=3, n_ieq_constr=2, **kwargs)
    def _evaluate(self, X, out, *args, **kwargs):
        nnu, nhydro, nng, npe, nco, nw, nso = X["nnu"], X["nhydro"], X["nng"], X["npe"], X["nco"], X["nw"], X["nso"] 

        f1 = -1*(pco*nco +pw*nw +pso*nso + pnu*nnu +phydro*nhydro +png*nng + ppe*npe ) 
        f2 =  (ecco*nco +ecw*nw +ecso*nso + ecnu*nnu +echydro*nhydro +ecng*nng + ecpe*npe ) 
        f3 =  (enco*nco +enw*nw +enso*nso + ennu*nnu +enhydro*nhydro +enng*nng + enpe*npe ) 

        g1  = f1-Power1
        #g2  = phydro+pw+pso -0.30*Power1
        g2  = Power1+Power2-f1

        out["F"] = [f1, f2, f3 ]
        out["G"]=  [g1 ,g2]
        

In [ ]:
from pymoo.visualization.scatter import Scatter
from pymoo.algorithms.moo.nsga2 import NSGA2, RankAndCrowdingSurvival
from pymoo.core.mixed import MixedVariableMating, MixedVariableGA, MixedVariableSampling, MixedVariableDuplicateElimination
from pymoo.optimize import minimize
problem=MultiObjectiveMixedVariableProblem()
algorithm = NSGA2(pop_size=50,
                  sampling=MixedVariableSampling(),
                  mating=MixedVariableMating(eliminate_duplicates=MixedVariableDuplicateElimination()),
                  eliminate_duplicates=MixedVariableDuplicateElimination(),
                  )
res = minimize(problem,
               algorithm,
               ('n_gen', 100),
               seed=1,
               verbose=False)



#plot = Scatter()
#plot.add(problem.pareto_front())
#plot.add(res.F, facecolor="none", edgecolor="red")
#plot.show()

In [ ]:
!pip install plotly

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
print(res.X)

[{'nnu': 96, 'nhydro': 528, 'nng': 129, 'npe': 6, 'nco': 190, 'nw': 83, 'nso': 226}
 {'nnu': 2, 'nhydro': 9, 'nng': 66, 'npe': 395, 'nco': 16, 'nw': 63, 'nso': 635}
 {'nnu': 0, 'nhydro': 7, 'nng': 100, 'npe': 375, 'nco': 1, 'nw': 19, 'nso': 355}
 {'nnu': 4, 'nhydro': 45, 'nng': 53, 'npe': 285, 'nco': 223, 'nw': 856, 'nso': 158}
 {'nnu': 76, 'nhydro': 495, 'nng': 64, 'npe': 0, 'nco': 11, 'nw': 458, 'nso': 155}
 {'nnu': 7, 'nhydro': 123, 'nng': 93, 'npe': 308, 'nco': 168, 'nw': 816, 'nso': 338}
 {'nnu': 11, 'nhydro': 980, 'nng': 279, 'npe': 59, 'nco': 141, 'nw': 914, 'nso': 517}
 {'nnu': 40, 'nhydro': 692, 'nng': 40, 'npe': 63, 'nco': 231, 'nw': 860, 'nso': 629}
 {'nnu': 53, 'nhydro': 624, 'nng': 6, 'npe': 45, 'nco': 988, 'nw': 832, 'nso': 981}
 {'nnu': 76, 'nhydro': 495, 'nng': 66, 'npe': 0, 'nco': 776, 'nw': 569, 'nso': 631}
 {'nnu': 84, 'nhydro': 516, 'nng': 804, 'npe': 9, 'nco': 878, 'nw': 564, 'nso': 161}
 {'nnu': 4, 'nhydro': 980, 'nng': 231, 'npe': 88, 'nco': 1, 'nw': 24, 'nso': 2

In [ ]:
print(res.F)

[[-8.13663272e+06  3.37142671e+14  2.17512302e+19]
 [-8.17700529e+06  4.96069152e+13  6.70814927e+20]
 [-7.59542338e+06  4.08581448e+13  6.36639061e+20]
 [-7.20284676e+06  6.14551954e+13  4.85694141e+20]
 [-7.22719916e+06  2.82907643e+14  1.04213139e+19]
 [-8.19989930e+06  8.16641512e+13  5.25725495e+20]
 [-8.13654088e+06  1.78957266e+14  1.13163553e+20]
 [-8.14566192e+06  2.21898437e+14  1.18272571e+20]
 [-8.09348108e+06  2.47139017e+14  8.81593572e+19]
 [-7.38505744e+06  2.85079535e+14  1.11075310e+19]
 [-8.08106077e+06  3.10799842e+14  2.72118309e+19]
 [-7.26726992e+06  1.47480556e+14  1.60732333e+20]
 [-7.58764281e+06  1.30951582e+14  2.66500803e+20]
 [-7.70067196e+06  1.29622105e+14  3.22415243e+20]
 [-7.93926169e+06  1.64337970e+14  2.00095240e+20]
 [-8.11144824e+06  2.40033314e+14  1.01604595e+20]
 [-8.15469389e+06  2.22156242e+14  1.18767960e+20]
 [-7.75413131e+06  1.39410354e+14  2.17130809e+20]
 [-7.64395493e+06  8.37457751e+13  4.51778873e+20]
 [-7.93340414e+06  2.76689512e+

In [ ]:
import plotly.express as px
import plotly.graph_objects as go


In [ ]:
import pandas as pd
df = res.F
dict = {'power':df[:,0],
        'economic':df[:,1],
        'environmental':df[:,2]
       }
dataf = pd.DataFrame(dict)
  
display(dataf)
fig = px.scatter_3d( x=df[:,0], y=df[:,1], z=df[:,2])

fig.show()

power      economic  environmental
0  -8.136633e+06  3.371427e+14   2.175123e+19
1  -8.177005e+06  4.960692e+13   6.708149e+20
2  -7.595423e+06  4.085814e+13   6.366391e+20
3  -7.202847e+06  6.145520e+13   4.856941e+20
4  -7.227199e+06  2.829076e+14   1.042131e+19
5  -8.199899e+06  8.166415e+13   5.257255e+20
6  -8.136541e+06  1.789573e+14   1.131636e+20
7  -8.145662e+06  2.218984e+14   1.182726e+20
8  -8.093481e+06  2.471390e+14   8.815936e+19
9  -7.385057e+06  2.850795e+14   1.110753e+19
10 -8.081061e+06  3.107998e+14   2.721183e+19
11 -7.267270e+06  1.474806e+14   1.607323e+20
12 -7.587643e+06  1.309516e+14   2.665008e+20
13 -7.700672e+06  1.296221e+14   3.224152e+20
14 -7.939262e+06  1.643380e+14   2.000952e+20
15 -8.111448e+06  2.400333e+14   1.016046e+20
16 -8.154694e+06  2.221562e+14   1.187680e+20
17 -7.754131e+06  1.394104e+14   2.171308e+20
18 -7.643955e+06  8.374578e+13   4.517789e+20
19 -7.933404e+06  2.766895e+14   2.189680e+19
20 -7.493130e+06  1.566765e+14   1.643620e+20
21 -7.668299e+06  1.552139e+14   1.879993e+20
22 -7.452126e+06  1.277971e+14   3.019067e+20
23 -7.495449e+06  7.139325e+13   4.929526e+20
24 -7.296045e+06  1.056293e+14   2.928815e+20
25 -7.256446e+06  1.286927e+14   2.424971e+20
26 -8.130292e+06  1.241347e+14   3.943289e+20
27 -7.845538e+06  6.320395e+13   5.905852e+20
28 -7.858587e+06  6.893107e+13   5.251746e+20
29 -8.157271e+06  6.086581e+13   6.240658e+20
30 -7.835122e+06  3.225492e+14   2.129545e+19
31 -8.013632e+06  2.467201e+14   8.137169e+19
32 -7.959091e+06  1.441519e+14   2.190421e+20
33 -8.057909e+06  3.360223e+14   2.153852e+19
34 -7.677574e+06  3.142450e+14   2.122371e+19
35 -8.160794e+06  2.783168e+14   3.789197e+19
36 -7.980255e+06  8.984920e+13   4.670485e+20
37 -7.535785e+06  1.444317e+14   1.977359e+20
38 -7.329756e+06  1.095457e+14   3.772074e+20
39 -7.907396e+06  1.000586e+14   4.221264e+20
40 -7.401640e+06  6.119022e+13   5.712921e+20
41 -7.325209e+06  1.108177e+14   2.860945e+20
42 -7.405543e+06  8.801829e+13   4.210664e+20
43 -7.397228e+06  1.201676e+14   3.348476e+20
44 -8.166460e+06  5.086485e+13   6.641725e+20
45 -7.432166e+06  8.714794e+13   4.277427e+20
46 -7.925257e+06  1.407908e+14   3.470859e+20
47 -8.038863e+06  9.049364e+13   4.687912e+20
48 -8.122730e+06  5.098374e+13   6.374567e+20
49 -7.340301e+06  9.524937e+13   3.815229e+20

In [ ]:
import plotly.express as px

fig = px.scatter_3d(dataf, x='power', y='economic', z='environmental')
fig.show()

In [ ]:
import numpy as np
weights = np.array([0.1, 0.6, 0.3])
from pymoo.decomposition.asf import ASF
import plotly.graph_objects as go
import numpy as np
decomp = ASF()
i = decomp.do(df, 1/weights).argmin()
print("Best regarding ASF: Point \ni = %s\nF = %s" % (i, df[i]))

Best regarding ASF: Point 
i = 4
F = [-7.22719916e+06  2.82907643e+14  1.04213139e+19]


In [ ]:
from pymoo.visualization.scatter import Scatter
from pymoo.algorithms.moo.nsga2 import RankAndCrowdingSurvival
from pymoo.core.mixed import MixedVariableGA
from pymoo.optimize import minimize

problem = MultiObjectiveMixedVariableProblem()

algorithm = MixedVariableGA(pop_size=50, survival=RankAndCrowdingSurvival())

res = minimize(problem,
               algorithm,
               ('n_gen', 50),
               seed=1,
               verbose=False)

import pandas as pd
df = res.F
dict = {'power':df[:,0],
        'economic':df[:,1],
        'environmental':df[:,2]
       }
dataf = pd.DataFrame(dict)
  
display(dataf)
fig = px.scatter_3d(dataf, x='power', y='economic', z='environmental')
fig.show()

power      economic  environmental
0  -8.189372e+06  1.057241e+14   4.089921e+20
1  -7.298280e+06  9.013375e+13   3.674752e+20
2  -8.159993e+06  2.883533e+14   5.111332e+19
3  -8.197745e+06  1.871469e+14   1.747172e+20
4  -7.201046e+06  1.595767e+14   1.038538e+20
5  -7.259104e+06  2.105217e+14   1.339841e+19
6  -7.411703e+06  2.439061e+14   7.167310e+19
7  -8.049977e+06  1.987236e+14   1.161003e+20
8  -7.339551e+06  2.109504e+14   2.020798e+19
9  -7.352132e+06  1.292706e+14   2.070780e+20
10 -7.499280e+06  2.621909e+14   1.528300e+19
11 -7.680147e+06  2.661193e+14   2.089180e+19
12 -8.013435e+06  1.034510e+14   4.070718e+20
13 -7.860149e+06  2.046885e+14   7.445428e+19
14 -7.968195e+06  1.090636e+14   3.590160e+20
15 -7.909700e+06  2.788257e+14   1.413195e+19
16 -8.134450e+06  1.750660e+14   1.404481e+20
17 -7.582560e+06  1.681689e+14   1.045928e+20
18 -8.139342e+06  2.810868e+14   2.774206e+19
19 -7.930005e+06  1.930656e+14   1.159519e+20
20 -7.291554e+06  1.102169e+14   2.896039e+20
21 -8.092970e+06  1.327099e+14   2.715684e+20
22 -7.215420e+06  1.810725e+14   9.605308e+19
23 -7.941561e+06  1.337925e+14   2.463761e+20
24 -7.617776e+06  9.551335e+13   3.847804e+20
25 -7.829307e+06  1.563240e+14   1.873965e+20
26 -7.229684e+06  1.211999e+14   2.509012e+20
27 -8.157524e+06  2.883246e+14   5.102660e+19
28 -7.581261e+06  1.517536e+14   1.396213e+20
29 -7.382974e+06  1.050230e+14   3.125842e+20
30 -7.468887e+06  1.295990e+14   2.186731e+20
31 -7.776540e+06  1.076025e+14   3.416083e+20
32 -7.953741e+06  1.324326e+14   2.579951e+20
33 -7.799969e+06  1.547559e+14   1.534868e+20
34 -7.821788e+06  1.195587e+14   2.905725e+20
35 -7.857936e+06  1.009676e+14   3.902070e+20
36 -7.543109e+06  1.040020e+14   3.344668e+20
37 -7.377908e+06  1.338855e+14   1.868421e+20
38 -7.909840e+06  1.406081e+14   2.179555e+20
39 -7.557723e+06  1.157508e+14   2.704021e+20
40 -7.452736e+06  2.512227e+14   6.375242e+19
41 -7.696289e+06  1.057659e+14   3.698407e+20
42 -7.443201e+06  2.510886e+14   6.374447e+19
43 -7.447726e+06  1.376078e+14   1.707030e+20
44 -8.185478e+06  2.836349e+14   6.609428e+19
45 -7.766359e+06  1.527762e+14   1.532851e+20
46 -7.480726e+06  1.043829e+14   3.260371e+20
47 -7.411505e+06  1.052301e+14   3.126829e+20
48 -7.638732e+06  1.465133e+14   1.709046e+20
49 -7.337733e+06  1.826883e+14   9.662935e+19

In [ ]:
import numpy as np
weights = np.array([0.1, 0.6, 0.3])
from pymoo.decomposition.asf import ASF
import plotly.graph_objects as go
import numpy as np
decomp = ASF()
i = decomp.do(df, 1/weights).argmin()
print("Best regarding ASF: Point \ni = %s\nF = %s" % (i, df[i]))
import pandas as pd
dans = df[5,:]
print(dans)
fig = px.scatter_3d( x=[-7.20848904e+06], y=[2.19949925e+14], z=[1.34983988e+19])

fig.show()
#fig.show()



Best regarding ASF: Point 
i = 5
F = [-7.25910404e+06  2.10521656e+14  1.33984074e+19]
[-7.25910404e+06  2.10521656e+14  1.33984074e+19]


In [ ]:
print(res.X[i])

{'nnu': 27, 'nhydro': 995, 'nng': 356, 'npe': 0, 'nco': 111, 'nw': 407, 'nso': 201}
